# Generated by Django 5.2.8 on 2026-01-07 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('category', models.CharField(choices=[('news', 'News'), ('events', 'Events'), ('achievement', 'Achievement')], default='news', max_length=20)),
                ('event_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_events/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News and Event',
                'verbose_name_plural': 'News and Events',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
