# Generated by Django 5.2.8 on 2026-03-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_newsevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('internal', 'Internal')], default='public', max_length=10),
        ),
    ]
