# Generated by Django 5.2.8 on 2026-02-18 01:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='content',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('boys', 'NCC Army Boys'), ('girls', 'NCC Army Girls'), ('naval', 'NCC Army Naval')], default='boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
