# Generated by Django 5.2.8 on 2026-02-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_gallery_author_remove_gallery_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('boys', 'NCC Army Boys'), ('girls', 'NCC Army Girls'), ('naval', 'NCC Army Naval')], default='all', max_length=20),
        ),
    ]
