# Generated by Django 5.2.8 on 2026-02-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('boys', 'NCC Army Boys'), ('girls', 'NCC Army Girls'), ('naval', 'NCC Naval')], default='general', max_length=20),
        ),
    ]
