# Generated by Django 5.2.8 on 2026-03-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_gallery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('internal', 'Internal')], default='public', max_length=10),
        ),
    ]
