# Generated by Django 5.2.8 on 2026-03-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_gallery_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
