# Generated by Django 5.2.8 on 2025-11-26 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_faculty',
            field=models.ForeignKey(blank=True, help_text='Designate the Faculty advisor for this Cadet.', limit_choices_to={'role': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cadets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_higher_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CADET', 'Cadet'), ('FACULTY', 'Faculty')], default='CADET', max_length=50),
        ),
    ]
