# Generated by Django 5.2.8 on 2026-03-25 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usertag_usertagassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_faculty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_higher_faculty',
        ),
    ]
