# Generated by Django 5.2.8 on 2026-02-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='section',
            field=models.CharField(choices=[('slider', 'Slider'), ('about', 'About'), ('achievement', 'Achievement')], max_length=20),
        ),
    ]
