# Generated by Django 5.2.8 on 2026-01-15 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('PARADE', 'Parade'), ('DRILL', 'Drill & Training'), ('CAMP', 'Camp'), ('SOCIAL', 'Social Service'), ('DUTY', 'Special Duty'), ('EXAM', 'Exam'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('organized_by', models.CharField(blank=True, choices=[('UNIT', 'Unit'), ('GROUP_HQ', 'Group HQ'), ('DIRECTORATE', 'Directorate')], max_length=20, null=True)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_hours', models.DecimalField(decimal_places=2, help_text='Total hours / periods', max_digits=5)),
                ('parade_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'activity')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='participants',
            field=models.ManyToManyField(related_name='activities', through='attendance.Attendance', to=settings.AUTH_USER_MODEL),
        ),
    ]
