# Generated by Django 5.2.8 on 2026-01-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total hours / periods', max_digits=5),
        ),
    ]
